-- DEVELOPMENT SEED ONLY. Every generated tool is draft, source_type=demo-seed and confidence_score=0.
insert into public.categories(name,slug,description) values
('Video','video','AI video creation and editing'),('Image','image','AI image generation and editing'),('Writing','writing','AI writing and content tools'),('Coding','coding','AI software development tools'),('Voice','voice','AI voice and speech tools'),('Marketing','marketing','AI marketing workflows'),('Research','research','AI research and knowledge tools'),('Design','design','AI design and creative tools'),('Productivity','productivity','AI productivity assistants'),('Audio','audio','AI audio generation and editing'),('Presentations','presentations','AI presentation tools'),('Customer Support','customer-support','AI support and service tools'),('Data','data','AI data analysis tools'),('Education','education','AI learning tools'),('Legal','legal','AI legal workflow tools')
on conflict(slug) do nothing;
insert into public.companies(name,slug,description,verified) select 'Demo Company '||lpad(i::text,2,'0'),'demo-company-'||i,'Development seed company; not production data',false from generate_series(1,20)i on conflict(slug) do nothing;
insert into public.features(name,slug) select 'Seed Feature '||lpad(i::text,3,'0'),'seed-feature-'||i from generate_series(1,100)i on conflict(slug) do nothing;
insert into public.tools(name,slug,description,short_description,website_url,source_url,category_id,company_id,pricing_type,currency,verified,featured,status,health_score,quality_score,source_type,confidence_score,use_cases,platforms)
select 'Demo AI Tool '||lpad(i::text,3,'0'),'demo-ai-tool-'||i,'Development seed record. Replace with verified source data before publishing.','Development seed record; not published.', 'https://example.com/demo-ai-tool-'||i,'seed://demo-ai-tool-'||i,
 (select id from public.categories order by slug offset ((i-1)%15) limit 1),(select id from public.companies order by slug offset ((i-1)%20) limit 1),'freemium','USD',false,false,'draft',null,null,'demo-seed',0,array['development seed'],array['web'] from generate_series(1,100)i on conflict(slug) do nothing;
