import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BookOpen } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export const metadata: Metadata = { title: 'AI Tools Blog & Guides', description: 'Practical guides for choosing, comparing and using AI tools for work and creativity.', alternates: { canonical: '/blog' } }
export const dynamic = 'force-dynamic'
const fallback = [{ slug: 'how-to-choose-the-right-ai-tool', title: 'How to choose the right AI tool', excerpt: 'A practical framework for evaluating features, pricing, quality and fit.' }, { slug: 'best-ai-tools-for-content-creation', title: 'Best AI tools for content creation', excerpt: 'A decision guide for writing, images, video and voice workflows.' }, { slug: 'ai-tool-stack-for-developers', title: 'AI tool stack for developers', excerpt: 'How to combine coding assistants, agents and research tools.' }]
export default async function Blog() { let data: any[] = []; try { const db = await createClient(); const result = await db.from('articles').select('slug,title,excerpt,published_at').eq('status', 'published').order('published_at', { ascending: false }).limit(24); data = result.data || [] } catch (error) { console.error('Blog database unavailable', error) }; const posts = data.length ? data : fallback; return <main className="container" style={{ padding: '58px 0 90px' }}><div className="eyebrow">Guides & insights</div><h1 style={{ fontSize: 48, letterSpacing: '-.045em', margin: '7px 0' }}>AI tools, explained.</h1><p className="muted" style={{ maxWidth: 680, fontSize: 17 }}>Useful, decision-focused content to help you get more from AI software.</p><div className="tool-grid" style={{ marginTop: 30 }}>{posts.map((post: any) => <article className="card tool-card" key={post.slug}><div className="tool-logo"><BookOpen size={22} /></div><div className="eyebrow" style={{ marginTop: 18 }}>AI Guide</div><h2 style={{ fontSize: 21, margin: '6px 0' }}>{post.title}</h2><p className="muted">{post.excerpt}</p><Link href={`/blog/${post.slug}`} style={{ marginTop: 'auto', display: 'inline-flex', alignItems: 'center', gap: 6, color: '#b9c5ff' }}>Read guide <ArrowRight size={14} /></Link></article>)}</div></main> }
