import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireAdmin } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'

const schema = z.object({ title: z.string().trim().min(5).max(180), slug: z.string().regex(/^[a-z0-9-]+$/).max(180), excerpt: z.string().trim().min(20).max(500), content: z.string().trim().min(100).max(50000), seo_title: z.string().trim().max(180).nullable().optional(), seo_description: z.string().trim().max(300).nullable().optional(), status: z.enum(['draft', 'published']) })
const updateSchema = schema.extend({ id: z.string().uuid() })
export async function GET() { try { await requireAdmin(); const { data, error } = await (await createClient()).from('articles').select('id,title,slug,excerpt,content,status,published_at,updated_at').order('updated_at', { ascending: false }); if (error) throw error; return NextResponse.json({ articles: data || [] }) } catch { return NextResponse.json({ error: 'Forbidden' }, { status: 403 }) } }
export async function POST(request: Request) { try { const { user } = await requireAdmin(); const input = schema.parse(await request.json()); const db = await createClient(); const { data, error } = await db.from('articles').insert({ ...input, author_id: user.id, published_at: input.status === 'published' ? new Date().toISOString() : null }).select('id,title,slug,status').single(); if (error) throw error; return NextResponse.json({ article: data }, { status: 201 }) } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ error: 'Invalid article' }, { status: 400 }); return NextResponse.json({ error: 'Unable to create article' }, { status: 400 }) } }
export async function PATCH(request: Request) { try { await requireAdmin(); const input = updateSchema.parse(await request.json()); const { id, ...changes } = input; const db = await createClient(); const { data, error } = await db.from('articles').update({ ...changes, published_at: input.status === 'published' ? new Date().toISOString() : null, updated_at: new Date().toISOString() }).eq('id', id).select('id,title,slug,status').single(); if (error) throw error; return NextResponse.json({ article: data }) } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ error: 'Invalid article' }, { status: 400 }); return NextResponse.json({ error: 'Unable to update article' }, { status: 400 }) } }
