import './globals.css'
import Link from 'next/link'
import { ArrowRight, BookOpen, Grid2X2, GitCompareArrows, ShieldCheck, Sparkles } from 'lucide-react'
import { getProfile, getUser } from '@/lib/auth'
import { AuthNavMain } from '@/components/auth-nav-main'
import { GlobalSearch } from '@/components/global-search'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://ai-tools-intelligence-platform-iota.vercel.app'
export const metadata = { metadataBase: new URL(siteUrl), title: { default: 'AITools — Find the Best AI Software', template: '%s | AITools' }, description: 'Discover, compare and find the best AI tools for writing, coding, design, video, voice, research and business.', keywords: ['AI tools', 'AI tool finder', 'best AI tools', 'AI software directory'], alternates: { canonical: '/' }, openGraph: { type: 'website', siteName: 'AITools', title: 'Find the Right AI Tool for Any Job', description: 'AI-powered discovery, comparisons and curated software recommendations.', url: siteUrl }, twitter: { card: 'summary_large_image', title: 'AITools — Find the Best AI Software', description: 'Find the right AI tool for any task.' }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 } } }

const nav = [{ href: '/ai-finder', label: 'AI Finder', icon: Sparkles }, { href: '/tools', label: 'Tools', icon: Sparkles }, { href: '/categories', label: 'Categories', icon: Grid2X2 }, { href: '/compare', label: 'Compare', icon: GitCompareArrows }, { href: '/blog', label: 'Guides', icon: BookOpen }] as const

export default async function Layout({ children }: { children: React.ReactNode }) {
  const user = await getUser()
  const profile = await getProfile()
  const jsonLd = { '@context': 'https://schema.org', '@type': 'WebSite', name: 'AITools', url: siteUrl, description: 'AI-powered directory and finder for AI software.', potentialAction: { '@type': 'SearchAction', target: `${siteUrl}/tools?q={search_term_string}`, 'query-input': 'required name=search_term_string' } }
  return <html lang="en"><body><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="container nav-shell"><Link href="/" className="brand" aria-label="AITools home"><span className="brand-mark"><Sparkles size={17} /></span><span>AI<span>Tools</span></span></Link><nav className="main-nav" aria-label="Primary navigation">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href}><Icon size={16} /><span>{label}</span></Link>)}</nav><GlobalSearch /><AuthNavMain userEmail={user?.email} role={profile?.role} /></div></header><div id="main-content">{children}</div><footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark"><Sparkles size={16} /></span><span>AI<span>Tools</span></span></Link><p className="muted footer-copy">A smarter way to discover, compare and evaluate AI software.</p></div><div><h3>Explore</h3><Link href="/ai-finder">AI Finder</Link><Link href="/tools">AI Tools</Link><Link href="/categories">Categories</Link><Link href="/compare">Compare Tools</Link></div><div><h3>Resources</h3><Link href="/blog">AI Guides</Link><Link href="/submit-tool">Submit a tool</Link></div><div><h3>Trust</h3><Link href="/about">About AITools</Link><Link href="/privacy">Privacy</Link><div className="trust-note"><ShieldCheck size={15} /> Curated AI directory</div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} AITools</span><Link href="/ai-finder">Find your next AI tool <ArrowRight size={14} /></Link></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></body></html>
}
