import './globals.css'
import Link from 'next/link'
import { ArrowRight, BookOpen, Grid2X2, GitCompareArrows, ShieldCheck, Sparkles } from 'lucide-react'
import { getProfile, getUser } from '@/lib/auth'
import { AuthNavMain } from '@/components/auth-nav-main'
import { GlobalSearch } from '@/components/global-search'
import { MobileNav } from '@/components/mobile-nav'
import { getSiteUrl, SITE_DESCRIPTION, SITE_NAME } from '@/lib/site'

const siteUrl = getSiteUrl()
export const metadata = { metadataBase: new URL(siteUrl), title: { default: 'Eldevo — AI Tools Intelligence', template: '%s | Eldevo' }, description: SITE_DESCRIPTION, keywords: ['AI tools', 'AI tool finder', 'AI workflows', 'AI software directory'], alternates: { canonical: '/' }, openGraph: { type: 'website', siteName: SITE_NAME, title: 'Eldevo — AI Tools Intelligence', description: SITE_DESCRIPTION, url: siteUrl }, twitter: { card: 'summary_large_image', title: 'Eldevo — AI Tools Intelligence', description: SITE_DESCRIPTION }, robots: { index: true, follow: true, googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 } } }

const nav = [{ href: '/ai-finder', label: 'AI Finder', icon: Sparkles }, { href: '/tools', label: 'Tools', icon: Sparkles }, { href: '/categories', label: 'Categories', icon: Grid2X2 }, { href: '/compare', label: 'Compare', icon: GitCompareArrows }, { href: '/blog', label: 'Guides', icon: BookOpen }] as const

export default async function Layout({ children }: { children: React.ReactNode }) {
  const [user, profile] = await Promise.all([getUser(), getProfile()])
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Organization', name: SITE_NAME, url: siteUrl, logo: `${siteUrl}/favicon.svg` }, { '@type': 'WebSite', name: SITE_NAME, url: siteUrl, description: SITE_DESCRIPTION, potentialAction: { '@type': 'SearchAction', target: `${siteUrl}/tools?q={search_term_string}`, 'query-input': 'required name=search_term_string' } }] }
  return <html lang="en"><body><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><div className="container nav-shell"><Link href="/" className="brand" aria-label="Eldevo home"><span className="brand-mark"><Sparkles size={17} /></span><span>Eldevo</span></Link><nav className="main-nav" aria-label="Primary navigation">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href}><Icon size={16} /><span>{label}</span></Link>)}</nav><GlobalSearch /><div className="auth-actions"><AuthNavMain userEmail={user?.email} role={profile?.role} /></div><MobileNav /></div></header><div id="main-content">{children}</div><footer className="site-footer"><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark"><Sparkles size={16} /></span><span>Eldevo</span></Link><p className="muted footer-copy">AI tools intelligence for better decisions and workflows.</p></div><div><h3>Explore</h3><Link href="/ai-finder">AI Finder</Link><Link href="/tools">AI Tools</Link><Link href="/categories">Categories</Link><Link href="/compare">Compare Tools</Link></div><div><h3>Resources</h3><Link href="/blog">AI Guides</Link><Link href="/submit-tool">Submit a tool</Link></div><div><h3>Trust</h3><Link href="/about">About Eldevo</Link><Link href="/privacy">Privacy</Link><Link href="/affiliate-disclosure">Affiliate disclosure</Link><div className="trust-note"><ShieldCheck size={15} /> Curated AI directory</div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Eldevo</span><Link href="/ai-finder">Find your next AI tool <ArrowRight size={14} /></Link></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></body></html>
}
