'use client'

import Link from 'next/link'
import { FileText, Grid2X2, Search, Wrench } from 'lucide-react'
import { FormEvent, useEffect, useRef, useState } from 'react'

type Results = { tools: { name: string; slug: string; short_description: string | null }[]; categories: { name: string; slug: string; description: string | null }[]; articles: { title: string; slug: string; excerpt: string | null }[] }
const emptyResults: Results = { tools: [], categories: [], articles: [] }

export function GlobalSearch() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<Results>(emptyResults)
  const [open, setOpen] = useState(false)
  const wrapper = useRef<HTMLDivElement>(null)
  useEffect(() => { if (query.trim().length < 2) { setResults(emptyResults); return }; const controller = new AbortController(); const timer = window.setTimeout(async () => { try { const response = await fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }); if (response.ok) setResults(await response.json()) } catch (error) { if ((error as Error).name !== 'AbortError') console.error(error) } }, 180); return () => { window.clearTimeout(timer); controller.abort() } }, [query])
  useEffect(() => { const close = (event: MouseEvent) => { if (wrapper.current && !wrapper.current.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim()) window.location.href = `/tools?q=${encodeURIComponent(query.trim())}` }
  const hasResults = results.tools.length + results.categories.length + results.articles.length > 0
  const itemStyle = { display: 'block', padding: '9px 12px', borderRadius: 9 }
  return <div ref={wrapper} style={{ position: 'relative', flex: '0 1 320px', minWidth: 160 }}><form onSubmit={submit} role="search" style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 8px', border: '1px solid var(--line)', borderRadius: 12, background: '#081321' }}><Search size={16} aria-hidden="true" /><input value={query} onChange={(event) => { setQuery(event.target.value); setOpen(true) }} onFocus={() => setOpen(true)} placeholder="Search tools..." aria-label="Search tools, categories and guides" style={{ border: 0, background: 'transparent', padding: '7px 0', minWidth: 0 }} /><button type="submit" aria-label="Submit search" style={{ border: 0, background: 'transparent', color: 'var(--muted)', cursor: 'pointer', padding: 4 }}>Search</button></form>{open && query.trim().length >= 2 && <div role="listbox" aria-label="Search suggestions" style={{ position: 'absolute', top: 'calc(100% + 8px)', left: 0, right: 0, zIndex: 60, padding: 8, border: '1px solid var(--line)', borderRadius: 14, background: '#0c1728', boxShadow: '0 18px 45px rgba(0,0,0,.35)' }}>{!hasResults ? <p className="muted" style={{ padding: '8px 12px', fontSize: 13 }}>No matches yet. Press Enter to search the directory.</p> : <>{results.tools.length > 0 && <div><div className="eyebrow" style={{ display: 'flex', gap: 5, padding: '6px 12px' }}><Wrench size={13} /> Tools</div>{results.tools.map((tool) => <Link href={`/tools/${tool.slug}`} key={tool.slug} onClick={() => setOpen(false)} style={itemStyle}><strong>{tool.name}</strong><span className="muted" style={{ display: 'block', fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{tool.short_description}</span></Link>)}</div>}{results.categories.length > 0 && <div><div className="eyebrow" style={{ display: 'flex', gap: 5, padding: '6px 12px' }}><Grid2X2 size={13} /> Categories</div>{results.categories.map((category) => <Link href={`/categories/${category.slug}`} key={category.slug} onClick={() => setOpen(false)} style={itemStyle}><strong>{category.name}</strong><span className="muted" style={{ display: 'block', fontSize: 12 }}>{category.description}</span></Link>)}</div>}{results.articles.length > 0 && <div><div className="eyebrow" style={{ display: 'flex', gap: 5, padding: '6px 12px' }}><FileText size={13} /> Guides</div>{results.articles.map((article) => <Link href={`/blog/${article.slug}`} key={article.slug} onClick={() => setOpen(false)} style={itemStyle}><strong>{article.title}</strong><span className="muted" style={{ display: 'block', fontSize: 12 }}>{article.excerpt}</span></Link>)}</div>}</>}</div>}</div>
}
