'use client'

import { useState } from 'react'

type Category = { id: string; name: string }
export function SubmissionForm({ categories }: { categories: Category[] }) {
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); const payload = { name: form.get('name'), website_url: form.get('website_url'), description: form.get('description'), category_id: form.get('category_id') || null, pricing_type: form.get('pricing_type') || null, logo_url: form.get('logo_url') || null, features: String(form.get('features') || '').split(',').map((item) => item.trim()).filter(Boolean), use_cases: String(form.get('use_cases') || '').split(',').map((item) => item.trim()).filter(Boolean) }; try { const response = await fetch('/api/submissions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (response.status === 401) { window.location.href = `/auth/sign-in?next=${encodeURIComponent(window.location.pathname)}`; return }; setMessage(response.ok ? 'Submission received. Our team will review it before publication.' : data.error || 'Unable to submit this tool.') } finally { setBusy(false) } }
  return <form className="card" style={{ padding: 28, marginTop: 28, display: 'grid', gap: 16 }} onSubmit={submit}><label>Tool name<input name="name" required /></label><label>Website URL<input name="website_url" type="url" required /></label><label>Description<textarea name="description" rows={5} minLength={30} required placeholder="What does it do, who is it for, and what makes it different?" /></label><label>Category<select name="category_id" defaultValue=""><option value="">Choose a category</option>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Pricing<input name="pricing_type" placeholder="Free, freemium, paid, or unknown" /></label><label>Logo URL<input name="logo_url" type="url" placeholder="Optional official logo URL" /></label><label>Features<input name="features" placeholder="API, text to video, collaboration" /><small className="muted">Separate features with commas.</small></label><label>Use cases<input name="use_cases" placeholder="TikTok videos, product demos" /><small className="muted">Separate use cases with commas.</small></label><button className="btn btn-primary" type="submit" disabled={busy}>{busy ? 'Submitting...' : 'Submit for review'}</button>{message && <p className="muted" role="status">{message}</p>}</form>
}
