import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { cookies } from 'next/headers'
import { ArrowRight, CheckCircle2, ExternalLink } from 'lucide-react'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { FavoriteButton } from '@/components/favorite-button'
import { ReviewForm } from '@/components/review-form'
import { getSiteUrl } from '@/lib/site'
import { normalizeLocale, LOCALE_COOKIE } from '@/lib/i18n'

type Tool = { id:string; name:string; name_ar:string|null; slug:string; description:string; description_ar:string|null; short_description:string; short_description_ar:string|null; website_url:string; logo_url:string|null; pricing_type:string|null; starting_price:number|null; currency:string|null; rating:number|null; review_count:number; verified:boolean; health_score:number|null; last_verified_at:string|null; use_cases:string[]; use_cases_ar:string[]; platforms:string[]; pros:string[]; pros_ar:string[]; cons:string[]; cons_ar:string[]; source_url:string|null; category:{id:string;name:string;name_ar:string|null;slug:string}|null; features:{name:string;slug:string}[]; pricing_plans:{name:string;price:number|null;currency:string;billing_period:string|null;is_free:boolean;features:unknown}[] }
type Review = { id:string; rating:number; title:string; body:string; pros:string[]; cons:string[]; created_at:string }

async function getTool(slug:string) {
  try {
    const db=await createClient()
    const {data}=await db.from('tools').select('id,name,name_ar,slug,description,description_ar,short_description,short_description_ar,website_url,logo_url,pricing_type,starting_price,currency,rating,review_count,verified,health_score,last_verified_at,use_cases,use_cases_ar,platforms,pros,pros_ar,cons,cons_ar,source_url,category:categories(id,name,name_ar,slug),features:tool_features(feature:features(name,slug)),pricing_plans(name,price,currency,billing_period,is_free,features)').eq('slug',slug).eq('status','published').maybeSingle()
    if(!data)return null
    const tool={...data,category:Array.isArray(data.category)?data.category[0]||null:data.category,features:(data.features||[]).map((item:any)=>item.feature).filter(Boolean),pricing_plans:data.pricing_plans||[]} as Tool
    const [relatedResult,reviewsResult]=await Promise.all([
      tool.category?db.from('tools').select('id,name,name_ar,slug,short_description,short_description_ar,rating,pricing_type').eq('category_id',tool.category.id).eq('status','published').neq('id',tool.id).order('rating',{ascending:false,nullsFirst:false}).limit(4):Promise.resolve({data:[]}),
      db.from('reviews').select('id,rating,title,body,pros,cons,created_at').eq('tool_id',tool.id).eq('status','approved').order('created_at',{ascending:false}).limit(20)
    ])
    return {tool,related:relatedResult.data||[],reviews:(reviewsResult.data||[]) as Review[]}
  }catch(error){console.error('Tool lookup failed',error);return null}
}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const result=await getTool((await params).slug);if(!result)return{};const {tool}=result;return{title:`${tool.name} Review 2026 — Features, Pricing & Alternatives`,description:tool.short_description,alternates:{canonical:`/tools/${tool.slug}`},openGraph:{title:`${tool.name} Review 2026`,description:tool.short_description,type:'article',images:tool.logo_url?[tool.logo_url]:[]}}}

export default async function ToolPage({params}:{params:Promise<{slug:string}>}){
  const locale=normalizeLocale((await cookies()).get(LOCALE_COOKIE)?.value);const ar=locale==='ar'
  const result=await getTool((await params).slug);if(!result)notFound();const {tool,related,reviews}=result;const siteUrl=getSiteUrl()
  const name=ar?(tool.name_ar||tool.name):tool.name;const description=ar?(tool.description_ar||tool.description):tool.description;const shortDescription=ar?(tool.short_description_ar||tool.short_description):tool.short_description;const categoryName=ar?(tool.category?.name_ar||tool.category?.name):tool.category?.name;const useCases=ar?(tool.use_cases_ar.length?tool.use_cases_ar:tool.use_cases):tool.use_cases;const pros=ar?(tool.pros_ar.length?tool.pros_ar:tool.pros):tool.pros;const cons=ar?(tool.cons_ar.length?tool.cons_ar:tool.cons):tool.cons
  const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:ar?'أدوات الذكاء الاصطناعي':'AI Tools',item:`${siteUrl}/tools`},...(tool.category?[{'@type':'ListItem',position:2,name:categoryName,item:`${siteUrl}/categories/${tool.category.slug}`}]:[]),{'@type':'ListItem',position:tool.category?3:2,name,item:`${siteUrl}/tools/${tool.slug}`}]}
  const application:Record<string,unknown>={'@context':'https://schema.org','@type':'SoftwareApplication',name,description:shortDescription,applicationCategory:categoryName||'AI software',operatingSystem:tool.platforms.length?tool.platforms.join(', '):'Web',url:`${siteUrl}/tools/${tool.slug}`,offers:tool.starting_price!==null?{'@type':'Offer',price:tool.starting_price,priceCurrency:tool.currency||'USD'}:undefined}
  if(tool.rating!==null&&tool.review_count>0)application.aggregateRating={'@type':'AggregateRating',ratingValue:tool.rating,ratingCount:tool.review_count,bestRating:5,worstRating:1}
  return <main className="container" style={{padding:'45px 0 100px'}}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(application)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
    <nav className="muted" aria-label={ar?'مسار التنقل':'Breadcrumb'}><Link href="/tools">{ar?'أدوات الذكاء الاصطناعي':'AI Tools'}</Link>{tool.category&&<> / <Link href={`/categories/${tool.category.slug}`}>{categoryName}</Link></>} / {name}</nav>
    <section className="card" style={{padding:30,marginTop:16}}><div style={{display:'flex',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}>{tool.logo_url&&<Image src={tool.logo_url} alt={`${name} logo`} width={72} height={72} style={{borderRadius:16,objectFit:'cover'}}/>}{!tool.logo_url&&<div className="tool-logo" aria-hidden="true">{name.slice(0,1)}</div>}<div style={{flex:1,minWidth:240}}><div className="eyebrow">{categoryName|| (ar?'برنامج ذكاء اصطناعي':'AI software')}</div><h1 style={{fontSize:'clamp(36px,5vw,54px)',margin:'3px 0 8px'}}>{name}</h1><p className="muted" style={{fontSize:18,margin:0}}>{shortDescription}</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:14}}><span>★ {tool.rating===null?(ar?'لا يوجد تقييم بعد':'No rating yet'):`${tool.rating} (${tool.review_count} ${ar?'تقييم':'reviews'})`}</span><span>{ar?({free:'مجاني',freemium:'مجاني مع ميزات مدفوعة',paid:'مدفوع',free_trial:'تجربة مجانية',contact_sales:'تواصل مع المبيعات'}[tool.pricing_type||'']||'السعر غير معروف'):(tool.pricing_type||'Pricing not verified')}</span>{tool.verified&&<span className="badge"><CheckCircle2 size={13}/> {ar?'موثقة':'Verified'}</span>}{tool.last_verified_at&&<span className="muted">{ar?'آخر تحديث':'Updated'} {new Date(tool.last_verified_at).toLocaleDateString(ar?'ar-SA':'en-US')}</span>}</div></div></div><p style={{fontSize:18,lineHeight:1.75,marginTop:26}}>{description}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="btn btn-primary" href={`/go/${tool.slug}`} target="_blank" rel="noopener noreferrer">{ar?'زيارة الموقع الرسمي':'Visit official website'} <ExternalLink size={15}/></Link><Link className="btn btn-secondary" href={`/compare?tool=${tool.slug}`}>{ar?'مقارنة':'Compare'}</Link><FavoriteButton toolId={tool.id}/></div></section>
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:18,marginTop:18}}><div className="card" style={{padding:24}}><h2>{ar?'الميزات':'Features'}</h2>{tool.features.length?<ul>{tool.features.map(feature=><li key={feature.slug}>{feature.name}</li>)}</ul>:<p className="muted">{ar?'لا توجد بيانات ميزات موثقة بعد.':'No verified feature data yet.'}</p>}</div><div className="card" style={{padding:24}}><h2>{ar?'الأسعار':'Pricing'}</h2>{tool.pricing_plans.length?<ul>{tool.pricing_plans.map(plan=><li key={plan.name}><strong>{plan.name}</strong> — {plan.is_free?(ar?'مجاني':'Free'):plan.price!==null?`${plan.currency} ${plan.price}${plan.billing_period?`/${plan.billing_period}`:''}`:(ar?'تواصل مع مزود الخدمة':'Contact provider')}</li>)}</ul>:<p className="muted">{ar?'لم يتم التحقق من الأسعار بعد. تحقق من الموقع الرسمي قبل الشراء.':'Pricing has not been verified yet. Check the official website before purchasing.'}</p>}</div><div className="card" style={{padding:24}}><h2>{ar?'الأفضل من أجله':'Best for'}</h2>{useCases.length?<ul>{useCases.map(item=><li key={item}>{item}</li>)}</ul>:<p className="muted">{ar?'لا توجد حالات استخدام موثقة بعد.':'No verified use cases yet.'}</p>}<h3>{ar?'المنصات':'Platforms'}</h3><p>{tool.platforms.length?tool.platforms.join(', '):(ar?'غير موثقة':'Not verified')}</p></div></section>
    <section className="card" style={{padding:24,marginTop:18}}><h2>{ar?'المزايا والقيود':'Pros and limitations'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:24}}><div><h3>{ar?'نقاط القوة':'Strengths'}</h3>{pros.length?<ul>{pros.map(item=><li key={item}>{item}</li>)}</ul>:<p className="muted">{ar?'لا توجد مزايا موثقة بعد.':'No verified strengths yet.'}</p>}</div><div><h3>{ar?'القيود':'Limitations'}</h3>{cons.length?<ul>{cons.map(item=><li key={item}>{item}</li>)}</ul>:<p className="muted">{ar?'لا توجد قيود موثقة بعد.':'No verified limitations yet.'}</p>}</div></div></section>
    <section style={{marginTop:34}}><div className="section-head"><div><div className="eyebrow">{ar?'بدائل':'Alternatives'}</div><h2>{ar?'أدوات مشابهة يمكنك التفكير بها':'Similar tools to consider'}</h2></div><Link className="btn btn-secondary" href={`/categories/${tool.category?.slug||''}`}>{ar?'تصفح التصنيف':'Browse category'} <ArrowRight size={15}/></Link></div>{related.length?<div className="tool-grid">{related.map((item:any)=>{const relatedName=ar?(item.name_ar||item.name):item.name;const relatedDescription=ar?(item.short_description_ar||item.short_description):item.short_description;return <article className="card tool-card" key={item.id}><h3 style={{marginTop:0}}>{relatedName}</h3><p className="muted">{relatedDescription}</p><div style={{marginTop:'auto',display:'flex',justifyContent:'space-between',fontSize:13}}><span>★ {item.rating??(ar?'بدون تقييم':'Unrated')}</span><Link href={`/compare/${[tool.slug,item.slug].sort().join('-vs-')}`}>{ar?'مقارنة':'Compare'} <ArrowRight size={13}/></Link></div></article>})}</div>:<div className="card" style={{padding:22}}><p className="muted">{ar?'لا توجد أدوات منشورة مشابهة في هذا التصنيف بعد.':'No similar published tools are available in this category yet.'}</p></div>}</section>
    <section style={{marginTop:34}}><div className="section-head"><div><div className="eyebrow">{ar?'تجارب المجتمع':'Community evidence'}</div><h2>{ar?'المراجعات':'Reviews'}</h2></div><span className="muted">{reviews.length} {ar?(reviews.length===1?'مراجعة معتمدة':'مراجعات معتمدة'):(reviews.length===1?'approved review':'approved reviews')}</span></div>{reviews.length?<div style={{display:'grid',gap:14}}>{reviews.map(review=><article className="card" style={{padding:22}} key={review.id}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><h3 style={{margin:0}}>{review.title}</h3><strong>★ {review.rating}/5</strong></div><p>{review.body}</p><small className="muted">{ar?'نُشرت':'Published'} {new Date(review.created_at).toLocaleDateString(ar?'ar-SA':'en-US')}</small></article>)}</div>:<div className="card" style={{padding:22}}><p className="muted">{ar?'لا توجد مراجعات معتمدة بعد. كن أول من يشارك تجربته.':'No approved reviews yet. Be the first to share an experience.'}</p></div>}<div style={{marginTop:18}}><ReviewForm toolId={tool.id}/></div></section>
  </main>
}
