import { createClient } from '@/lib/supabase/server';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import type { Metadata } from 'next';

async function getTool(slug:string){const db=await createClient();const {data}=await db.from('tools').select('id,name,slug,description,short_description,website_url,logo_url,pricing_type,starting_price,currency,rating,review_count,verified,featured,health_score,quality_score,last_verified_at,use_cases,platforms,pros,cons,source_url,category:categories(name,slug),features:tool_features(feature:features(name,slug)),pricing_plans(name,price,currency,billing_period,is_free,features)').eq('slug',slug).eq('status','published').single();if(!data)return null;return {...data,category:Array.isArray(data.category)?data.category[0]:data.category,features:(data.features||[]).map((x:any)=>x.feature).filter(Boolean)};}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const t=await getTool((await params).slug);if(!t)return{};return {title:`${t.name} — AI Tool Review`,description:t.short_description,alternates:{canonical:`/tools/${t.slug}`},openGraph:{title:t.name,description:t.short_description,type:'website',images:t.logo_url?[t.logo_url]:[]}};}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){const t=await getTool((await params).slug);if(!t)notFound();return <main className="container" style={{padding:'55px 0 100px'}}><div className="muted">AI TOOLS / {t.category?.name||'TOOL'}</div><section className="card" style={{padding:30,marginTop:16}}><div style={{display:'flex',gap:18,alignItems:'flex-start'}}>{t.logo_url&&<img src={t.logo_url} alt="" width={72} height={72} style={{borderRadius:16,objectFit:'cover'}}/>}<div style={{flex:1}}><h1 style={{fontSize:44,margin:'0 0 8px'}}>{t.name}{t.verified&&<span style={{fontSize:14,marginLeft:10}} className="btn btn-secondary">Verified</span>}</h1><p className="muted" style={{fontSize:18}}>{t.short_description}</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><span>★ {t.rating??'No rating yet'} {t.review_count?`(${t.review_count})`:''}</span><span>{t.pricing_type}</span>{t.last_verified_at&&<span>Verified {new Date(t.last_verified_at).toLocaleDateString()}</span>}</div></div></div><p style={{fontSize:18,lineHeight:1.7,marginTop:26}}>{t.description}</p><div style={{display:'flex',gap:10}}><Link className="btn btn-primary" href={`/go/${t.slug}`}>Try Tool</Link><Link className="btn btn-secondary" href={`/compare/${t.slug}`}>Compare</Link></div></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18,marginTop:18}}><div className="card" style={{padding:24}}><h2>Features</h2>{t.features.length?<ul>{t.features.map((f:any)=><li key={f.slug}>✓ {f.name}</li>)}</ul>:<p className="muted">No verified feature data yet.</p>}</div><div className="card" style={{padding:24}}><h2>Pricing</h2>{t.pricing_plans.length?<ul>{t.pricing_plans.map((p:any)=><li key={p.name}><strong>{p.name}</strong> — {p.is_free?'Free':p.price!=null?`${p.currency} ${p.price}${p.billing_period?`/${p.billing_period}`:''}`:'Contact sales'}</li>)}</ul>:<p className="muted">Pricing has not been verified yet.</p>}</div><div className="card" style={{padding:24}}><h2>Best for</h2>{t.use_cases?.length?<ul>{t.use_cases.map((x:string)=><li key={x}>{x}</li>)}</ul>:<p className="muted">No verified use-case data yet.</p>}</div></section>
<section className="card" style={{padding:24,marginTop:18}}><h2>Pros & limitations</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}><div><h3>Pros</h3>{t.pros?.length?<ul>{t.pros.map((x:string)=><li key={x}>✓ {x}</li>)}</ul>:<p className="muted">No verified pros yet.</p>}</div><div><h3>Limitations</h3>{t.cons?.length?<ul>{t.cons.map((x:string)=><li key={x}>• {x}</li>)}</ul>:<p className="muted">No verified limitations yet.</p>}</div></div></section>
</main>}