import { createHash } from 'crypto'
import { lookup } from 'dns/promises'
import { isIP } from 'net'
import { getAIProvider } from '../ai/provider'

export type ImportedTool = { name?: string; description?: string; short_description?: string; pricing?: unknown; features?: string[]; category?: string; source_url: string; confidence_score: number; source_type: 'public-page' }

function text(html: string) { return html.replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim() }
function disallowedByRobots(raw: string) { let active = false; for (const line of raw.split(/\r?\n/)) { const clean = line.split('#')[0].trim(); if (!clean) continue; const [key, value] = clean.split(':', 2).map((item) => item.trim().toLowerCase()); if (key === 'user-agent') active = value === '*'; else if (active && key === 'disallow' && value === '/') return true } return false }
function isPrivateAddress(address: string) { if (address === '::1' || address.startsWith('127.') || address.startsWith('10.') || address.startsWith('192.168.') || address.startsWith('169.254.')) return true; const parts = address.split('.').map(Number); return parts.length === 4 && parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31 }
async function assertPublicUrl(raw: string) { const url = new URL(raw); if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || (url.port && !['80', '443'].includes(url.port))) throw new Error('Only public HTTP(S) URLs are supported'); if (url.hostname === 'localhost' || url.hostname.endsWith('.local') || url.hostname === 'metadata.google.internal') throw new Error('Private network URLs are not supported'); const addresses = isIP(url.hostname) ? [url.hostname] : (await lookup(url.hostname, { all: true })).map((result) => result.address); if (addresses.some(isPrivateAddress)) throw new Error('Private network URLs are not supported'); return url }
async function fetchPublicPage(start: URL) { let current = start; for (let redirects = 0; redirects <= 5; redirects += 1) { const response = await fetch(current, { headers: { 'user-agent': 'AI-Tools-Intelligence-Platform/1.0 (+public-import)' }, redirect: 'manual', cache: 'no-store', signal: AbortSignal.timeout(15000) }); if (response.status >= 300 && response.status < 400) { const location = response.headers.get('location'); if (!location) throw new Error('Source returned an invalid redirect'); current = await assertPublicUrl(new URL(location, current).toString()); continue } return { response, url: current } } throw new Error('Source redirected too many times') }

export async function importPublicTool(rawUrl: string): Promise<ImportedTool> { const url = await assertPublicUrl(rawUrl); const robotsUrl = await assertPublicUrl(new URL('/robots.txt', url.origin).toString()); const robotsResponse = await fetch(robotsUrl, { cache: 'no-store', signal: AbortSignal.timeout(10000) }); if (robotsResponse.ok && disallowedByRobots(await robotsResponse.text())) throw new Error('Robots policy disallows automated import'); const { response, url: resolvedUrl } = await fetchPublicPage(url); if (!response.ok) throw new Error(`Source returned ${response.status}`); const html = await response.text(); if (html.length > 2_000_000) throw new Error('Source page is too large'); const plain = text(html).slice(0, 30000); const provider = getAIProvider(); if (!provider) { const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim(); return { name: title || undefined, source_url: resolvedUrl.toString(), source_type: 'public-page', confidence_score: title ? 20 : 0 } } const schema = { type: 'object', properties: { name: { type: 'string' }, description: { type: 'string' }, short_description: { type: 'string' }, pricing: { type: ['object', 'array', 'string', 'null'] }, features: { type: 'array', items: { type: 'string' } }, category: { type: 'string' }, confidence_score: { type: 'number' } }, additionalProperties: false }; const result = await provider.generateStructuredOutput<Omit<ImportedTool, 'source_url' | 'source_type'>>({ system: 'Extract only information explicitly present in the supplied public webpage text. Never infer pricing, ratings, user counts, features, or company facts. If uncertain, omit the field. Return confidence 0-100.', user: plain, schema }); return { ...result, source_url: resolvedUrl.toString(), source_type: 'public-page', confidence_score: Math.max(0, Math.min(100, result.confidence_score || 0)) } }
export function snapshotHash(content: string) { return createHash('sha256').update(content).digest('hex') }
