import { redirect } from 'next/navigation'
import { z } from 'zod'
import Link from 'next/link'
import { requireEditor } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'

const schema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().trim().min(2).max(160).regex(/^[a-z0-9-]+$/),website_url:z.string().url(),short_description:z.string().trim().min(10).max(300),description:z.string().trim().min(20),category_id:z.string().uuid(),pricing_type:z.enum(['free','freemium','paid','free_trial','contact_sales']),starting_price:z.string().optional(),currency:z.string().trim().length(3),logo_url:z.string().url().optional().or(z.literal('')),source_url:z.string().url().optional().or(z.literal('')),status:z.enum(['draft','published','archived']),verified:z.string().optional(),featured:z.string().optional()})

export default async function EditTool({params}:{params:Promise<{id:string}>}){try{await requireEditor()}catch{redirect('/auth/sign-in')}const{id}=await params;const db=await createClient();const[{data:tool},{data:categories}]=await Promise.all([db.from('tools').select('*').eq('id',id).single(),db.from('categories').select('id,name').order('name')]);if(!tool)redirect('/admin/tools');
async function save(formData:FormData){'use server';await requireEditor();const db=await createClient();const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error('Invalid tool data');const v=parsed.data;const{error}=await db.from('tools').update({name:v.name,slug:v.slug,website_url:v.website_url,short_description:v.short_description,description:v.description,category_id:v.category_id,pricing_type:v.pricing_type,starting_price:v.starting_price?Number(v.starting_price):null,currency:v.currency.toUpperCase(),logo_url:v.logo_url||null,source_url:v.source_url||null,status:v.status,verified:v.verified==='on',featured:v.featured==='on',updated_at:new Date().toISOString()}).eq('id',id);if(error)throw new Error('Unable to update tool');redirect('/admin/tools')}
async function remove(){'use server';await requireEditor();const db=await createClient();await db.from('tools').delete().eq('id',id);redirect('/admin/tools')}
return <main className="container" style={{padding:'55px 0'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><span className="muted">Catalog management</span><h1>Edit tool</h1></div><Link href="/admin/tools" className="btn btn-secondary">Back</Link></div><form action={save} className="card" style={{padding:28,maxWidth:950,marginTop:20,display:'grid',gap:16}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><label>Name<input name="name" defaultValue={tool.name}/></label><label>Slug<input name="slug" defaultValue={tool.slug}/></label><label>Website URL<input name="website_url" defaultValue={tool.website_url}/></label><label>Logo URL<input name="logo_url" defaultValue={tool.logo_url??''}/></label><label>Source URL<input name="source_url" defaultValue={tool.source_url??''}/></label><label>Category<select name="category_id" defaultValue={tool.category_id}>{(categories??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Pricing<select name="pricing_type" defaultValue={tool.pricing_type}>{['free','freemium','paid','free_trial','contact_sales'].map(x=><option key={x}>{x}</option>)}</select></label><label>Starting price<input name="starting_price" defaultValue={tool.starting_price??''} inputMode="decimal"/></label><label>Currency<input name="currency" defaultValue={tool.currency??'USD'}/></label><label>Status<select name="status" defaultValue={tool.status}>{['draft','published','archived'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Short description<input name="short_description" defaultValue={tool.short_description}/></label><label>Description<textarea name="description" rows={10} defaultValue={tool.description}/></label><div style={{display:'flex',gap:20}}><label><input name="verified" type="checkbox" defaultChecked={tool.verified}/> Verified</label><label><input name="featured" type="checkbox" defaultChecked={tool.featured}/> Featured</label></div><button className="btn btn-primary">Save changes</button></form><form action={remove} style={{marginTop:12}}><button className="btn btn-secondary" style={{color:'#fb7185'}}>Delete tool</button></form></main>}
