-- Authentication hardening and role-aware ownership.
alter table public.tools add column if not exists owner_id uuid references auth.users(id) on delete set null;
create index if not exists tools_owner_idx on public.tools(owner_id);
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create or replace function public.is_editor_or_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in('admin','editor')); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,display_name,avatar_url,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),new.raw_user_meta_data->>'avatar_url','user') on conflict(id) do update set full_name=coalesce(public.profiles.full_name,excluded.full_name),display_name=coalesce(public.profiles.display_name,excluded.display_name),avatar_url=coalesce(public.profiles.avatar_url,excluded.avatar_url),updated_at=now(); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security;
drop policy if exists "own profile" on public.profiles; drop policy if exists "admin profiles" on public.profiles; drop policy if exists "profiles own select" on public.profiles; drop policy if exists "profiles own update" on public.profiles; drop policy if exists "profiles admin select" on public.profiles;
create policy "profiles own select" on public.profiles for select using(id=auth.uid());
create policy "profiles admin select" on public.profiles for select using(public.is_admin());
revoke update on public.profiles from authenticated;
create or replace function public.update_own_profile(new_full_name text,new_avatar_url text) returns public.profiles language plpgsql security definer set search_path=public as $$ declare result public.profiles; begin if auth.uid() is null then raise exception 'UNAUTHENTICATED'; end if; update public.profiles set full_name=nullif(trim(new_full_name),''),display_name=nullif(trim(new_full_name),''),avatar_url=nullif(trim(new_avatar_url),''),updated_at=now() where id=auth.uid() returning * into result; return result; end; $$;
revoke all on function public.update_own_profile(text,text) from public; grant execute on function public.update_own_profile(text,text) to authenticated;
create or replace function public.set_user_role(target_user uuid,new_role public.user_role) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; if target_user=auth.uid() then raise exception 'SELF_ROLE_CHANGE_NOT_ALLOWED'; end if; if new_role='visitor' then raise exception 'INVALID_ROLE'; end if; update public.profiles set role=new_role,updated_at=now() where id=target_user; if not found then raise exception 'USER_NOT_FOUND'; end if; end; $$;
revoke all on function public.set_user_role(uuid,public.user_role) from public; grant execute on function public.set_user_role(uuid,public.user_role) to authenticated;
alter table public.tools enable row level security;
drop policy if exists "admin tools" on public.tools; drop policy if exists "editor tools" on public.tools; drop policy if exists "tool owner update" on public.tools; drop policy if exists "tool owner insert" on public.tools;
create policy "admin tools" on public.tools for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "editor tools" on public.tools for all to authenticated using(public.is_editor_or_admin()) with check(public.is_editor_or_admin());
create policy "tool owner update" on public.tools for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "tool owner insert" on public.tools for insert to authenticated with check(owner_id=auth.uid());
alter table public.favorites enable row level security;
drop policy if exists "own favorites" on public.favorites; drop policy if exists "favorites own all" on public.favorites;
create policy "favorites own all" on public.favorites for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
alter table public.reviews enable row level security;
drop policy if exists "create reviews" on public.reviews; drop policy if exists "reviews authenticated insert" on public.reviews; drop policy if exists "reviews own update" on public.reviews; drop policy if exists "reviews own delete" on public.reviews; drop policy if exists "reviews moderators" on public.reviews;
create policy "reviews authenticated insert" on public.reviews for insert to authenticated with check(auth.uid()=user_id);
create policy "reviews own update" on public.reviews for update to authenticated using(auth.uid()=user_id and status='pending') with check(auth.uid()=user_id);
create policy "reviews own delete" on public.reviews for delete to authenticated using(auth.uid()=user_id and status='pending');
create policy "reviews moderators" on public.reviews for all to authenticated using(public.is_editor_or_admin()) with check(public.is_editor_or_admin());
alter table public.tool_claims enable row level security;
drop policy if exists "tool claims own select" on public.tool_claims; drop policy if exists "tool claims own insert" on public.tool_claims;
create policy "tool claims own select" on public.tool_claims for select to authenticated using(claimant_id=auth.uid() or public.is_editor_or_admin());
create policy "tool claims own insert" on public.tool_claims for insert to authenticated with check(claimant_id=auth.uid());
alter table public.admin_logs enable row level security;
drop policy if exists "admin logs admin read" on public.admin_logs;
create policy "admin logs admin read" on public.admin_logs for select to authenticated using(public.is_admin());
